#!/bin/bash
echo "════════════════════════════════════════════════════════════"
echo "  Push n360 Platform para GitHub"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Repositório: https://github.com/resper1965/n360"
echo ""
echo "PASSOS:"
echo ""
echo "1. Crie o repositório no GitHub:"
echo "   https://github.com/new"
echo ""
echo "   Repository name: n360"
echo "   Description: Security Information Orchestrator - GRC, SOC e NOC"
echo "   Private: ✅ (recomendado)"
echo "   NÃO inicialize com README"
echo ""
echo "2. Após criar, execute:"
echo ""
echo "   git push -u origin main"
echo ""
echo "3. Se pedir autenticação, use Personal Access Token:"
echo "   GitHub → Settings → Developer settings → Personal access tokens"
echo "   → Generate new token (classic)"
echo "   → Marque: repo (Full control)"
echo ""
echo "════════════════════════════════════════════════════════════"
